#version: '3.8'
#
#services:
#  app:
#      build:
#        context: ./
#        dockerfile: Dockerfile
#      volumes:
#        - /data/springboot-docker-compose-app
#      container_name: app
#      restart: always
#      ports:
#        - "8080:8080"
