spring:
  config:
    activate:
      on-profile: Prod

  datasource:
    username: db_lablims
    password: Beast666@0123
    url: jdbc:postgresql://85.31.233.72:5432/db_lablims

server:
  port: '8080'
#  ssl:
#    key-store: classpath:lablims.p12
#    key-store-password: Beast666@0123
