spring:
  config:
    activate:
      on-profile: Prod

  datasource:
    username: postgres
    password: Beast666@01
    url: jdbc:postgresql://localhost:5432/db_lablims

server:
  port: '443'
  ssl:
    key-store: classpath:lablims.p12
    key-store-password: Beast666@0123
